=== andres-201701/2021_LMSGI_AUF/pruebas/modelo.xsd
<?xml version="1.0"?>
<!--
auttor Andrés de Uña Fontana
Fecha 11/2/2021
validacion de elementos simples
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DAW"/>
                            <xs:enumeration value="ASIR"/>
                            <xs:enumeration value="DAM"/>
                            <xs:enumeration value="SMR"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nombreciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100"/>
                            <xs:pattern value="[A-ZÑ]([a-z A-ZñÑ])*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigopostal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{5}"/>
                        </xs:restriction>
                    </xs:simpleType> 
                </xs:element>
                <xs:element name="comentario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="collapse"/>
                        </xs:restriction>
                    </xs:simpleType> 
                </xs:element>
                <xs:element name="profesor">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="codP" type="xs:string">
                                <xs:restriction base=
                                    <xs:pattern value="[A-ZÑ]([a-z A-ZñÑ])*"/>
                                <xs:attribute name="modulo" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                        </xs:attribute>
                    </xs:complexType> 
                </xs:element>
                <xs:element name="temperatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="5"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="-50"/>
                            <xs:maxInclusive value="50"/>
                        </xs:restriction>
                    </xs:simpleType> 
                </xs:element>
                <xs:element name="codigoAsignatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="BBDD|LMSG|PROG|EDD|SINF"/>
                        </xs:restriction>
                    </xs:simpleType> 
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== andres-201701/2021_LMSGI_AUF/pruebas/modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='modelo.xsd'>
    <curso>1</curso>
    <ciclo>DAW</ciclo>
    <nombreciclo>Desarrollo de Aplicaciones Web</nombreciclo>
    <codigopostal>49600</codigopostal>
    <comentario> Este     ciclo     tiene     una     insercion     laboral de 100%</comentario>
    <profesor codP="ARN" modulo="LMSG">Amor Rodriguez</profesor>
    <temperatura>22.3</temperatura>
    <codigoAsignatura>EDD</codigoAsignatura>
</modelo>
