=== andres-201701/2021_LMSGI_AUF/examenes/ex02_202110309_andresdeUña/mapaestelar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT mapaestelar (constelacion*)>
<!ATTLIST mapaestelar
    xmlns:xsi CDATA #IMPLIED
     xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT constelacion (nombre, superficie, estrellas, objetos, colindantes+, observacion)>
<!ATTLIST constelacion 
            nombreLatin CDATA #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo, masBrillante)>
<!ATTLIST estrellas 
            numeroEstrellas CDATA #REQUIRED
>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante 
            luminosidad CDATA #REQUIRED
>
<!ELEMENT objetos (cumulos, nebulosas, galaxias, cuasares, lluviademeteoros+)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviademeteoros (#PCDATA)>
<!ELEMENT colindantes (#PCDATA)>
<!ELEMENT observacion (hemisferio, mes, hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ATTLIST hemisferio 
            valor ( norte | sur) #REQUIRED
>
<!ELEMENT mes (#PCDATA)>
<!ATTLIST mes 
            valor CDATA #REQUIRED
>
<!ELEMENT hora (#PCDATA)>
<!ATTLIST hora 
            valor CDATA #REQUIRED
>

=== andres-201701/2021_LMSGI_AUF/examenes/ex02_202110309_andresdeUña/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE mapaestelar SYSTEM "mapaestelar.dtd">

<mapaestelar
    xmlns:xsi="http://www.w3.org/2001/XMLSchema"
     xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
>
    <constelacion nombreLatin="Ursa maior">
        <nombre>La Osa Mayor</nombre>
        <superficie> 1300 grados cuadrados</superficie>
        <estrellas numeroEstrellas="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="1" >Alioth</masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false </cuasares>
            <lluviademeteoros>Kappa Ursa Mayoridas</lluviademeteoros>
            <lluviademeteoros>Lambda Ursa Mayoridas</lluviademeteoros>
            <lluviademeteoros>Psi Ursa Mayoridas</lluviademeteoros>
            <lluviademeteoros>Ursa Mayoridas de octubre</lluviademeteoros>
        </objetos>
        <colindantes>Bootes</colindantes>
        <colindantes>Camelopardalis</colindantes>
        <colindantes>Canes Venatici</colindantes>
        <colindantes>Draco</colindantes>
        <colindantes>Leo</colindantes>
        <colindantes>Leo Minor </colindantes>
        <colindantes>Lynx</colindantes>
        <observacion>
            <hemisferio valor="norte"></hemisferio>
            <mes valor="10"></mes>
            <hora valor="12:12:12"></hora>
        </observacion>
    </constelacion>
</mapaestelar>
