<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla[
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
    <!ELEMENT mundo (fila)>
    <!ELEMENT fila (continente,pais,capital)>


<mundo>
	<fila>
		<continente>Europa</continente>
		<pais>Alemania</pais>
		<capital>Berlin</capital>
	</fila>
	<fila>
		<continente>América</continente>
		<pais>Argentina</pais>
		<capital>Buenos Aires</capital>
	</fila>
        <fila>
		<continente>América</continente>
		<pais>Argentina</pais>
		<capital>Buenos Aires</capital>
	</fila>
        <fila>
		<continente>América</continente>
		<pais>Bahamas</pais>
		<capital>Nassau</capital>
	</fila>
         <fila>
		<continente>Asia</continente>
		<pais>Afganitan</pais>
		<capital>Kabul</capital>
	</fila>
	 <fila>
		<continente>Asia</continente>
		<pais>Arabia saudita</pais>
		<capital>Riad</capital>
	</fila>
	
	
	
	
</mundo>