=== andres-201701/2021_LMSGI_AUF/ud04/03.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT fecha (dia,mes,anyo)>
<!ELEMENT hechoshistoricos (descripcion, fecha)>
<!ELEMENT hechos (hechoshistoricos*)>

=== andres-201701/2021_LMSGI_AUF/ud04/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE hechos SYSTEM '03.dtd'>
 <hechos>
    <hechoshistoricos>
     <descripcion>Se funda Youtube</descripcion> 
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </hechoshistoricos>
    <hechoshistoricos>
     <descripcion>Se funda Google</descripcion> 
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </hechoshistoricos>
    <hechoshistoricos>
     <descripcion>Se funda Facebook</descripcion> 
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </hechoshistoricos>
</hechos>
