=== andres-201701/2021_LMSGI_AUF/ud04/13.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT formulario (datosPersonales, equipoFav, posicionFav,jugadoresFav)>
<!ATTLIST formulario
            xmlns:xsi CDATA #IMPLIED
            xsi:noNamespaceSchemaLocation CDATA #IMPLIED
> 
<!ELEMENT datosPersonales (nombre, apellidos, dni)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT equipoFav (entrenador)>
<!ATTLIST equipoFav
                equipo (RealMadrid|FCBarcelona|AtMadrid|Sevilla) #REQUIRED
>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT posicionFav (#PCDATA)>
<!ATTLIST posicionFav
                posicion (Delantero|Centrocampista|Defensa|Portero) #REQUIRED
>
<!ELEMENT jugadoresFav (jugador)+>
<!ELEMENT jugador (#PCDATA)>

=== andres-201701/2021_LMSGI_AUF/ud04/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<!DOCTYPE formulario SYSTEM "13.dtd">

<formulario
xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:noNamespaceSchemaLocation='13.xsd'>
    <datosPersonales>
        <nombre>Paco</nombre>
        <apellidos>Leon</apellidos>
        <dni>12345678J</dni>
    </datosPersonales>
    <equipoFav equipo="RealMadrid">
        <entrenador>ZZ</entrenador>
    </equipoFav>
    <posicionFav posicion="Delantero"/>
    <jugadoresFav>
        <jugador>Mbappe</jugador>
        <jugador>Cristiano</jugador>
    </jugadoresFav>
</formulario>
